GET http://localhost:5600/v1/events?page=1



###
POST http://localhost:3001/pdfmake
content-type: application/json

{
"name":"samantha",
"phone":"9813243989",
"dob":"01-23-1999",
"gender":"FEMALE",
"location":"Kapan",
"orgName":"prasuti"

}

